apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.general.name }}
  labels:
    app: {{ .Values.general.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.general.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.general.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.deployment.image }}
          ports:
            - containerPort: {{ .Values.service.port }}